### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by MrMinimal** [ArmoryBlender/Armory3d-First-Person-Controller#1]
Hi there!

I tried following the youtube tutorial but I don't have assets to go alongside. What license is this repo and can I use the character model for the tutorial? Are the models zlib or something else (CC0, CC-BY-SA etc.)?

Cheers

**Comment by ArmoryBlender** [comment]
Hey @MrMinimal !! You can use the stuff for anything you want. I put this stuff for learning purposes so you can use it for anything!
